//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automotriz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accesorio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accesorio()
        {
            this.AutoAccesorios = new HashSet<AutoAccesorio>();
        }
    
        public int IdAccesorio { get; set; }
        public string Serie { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> IdAccesorioList { get; set; }
        public Nullable<int> IdConcesinaria { get; set; }
    
        public virtual AccesorioList AccesorioList { get; set; }
        public virtual Concesinaria Concesinaria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoAccesorio> AutoAccesorios { get; set; }
    }
}
