//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automotriz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Automovil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Automovil()
        {
            this.AutoAccesorios = new HashSet<AutoAccesorio>();
            this.AutoClientes = new HashSet<AutoCliente>();
            this.Mantenimientoes = new HashSet<Mantenimiento>();
            this.Origen_Fabrica = new HashSet<Origen_Fabrica>();
            this.Origen_Traspaso = new HashSet<Origen_Traspaso>();
        }
    
        public int IdAutomovil { get; set; }
        public string Numero { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<decimal> PrecioCompra { get; set; }
        public Nullable<decimal> PrecioVenta { get; set; }
        public Nullable<decimal> PrecioTotal { get; set; }
        public Nullable<decimal> PrecioPromo { get; set; }
        public Nullable<int> IdAnios { get; set; }
        public Nullable<int> IdAutoModelo { get; set; }
        public Nullable<int> IdAutoColor { get; set; }
        public Nullable<int> IdAutoEstado { get; set; }
        public Nullable<int> IdConcesinaria { get; set; }
    
        public virtual Anio Anio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoAccesorio> AutoAccesorios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoCliente> AutoClientes { get; set; }
        public virtual AutoColorList AutoColorList { get; set; }
        public virtual AutoEstadoList AutoEstadoList { get; set; }
        public virtual AutoModelo AutoModelo { get; set; }
        public virtual Concesinaria Concesinaria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mantenimiento> Mantenimientoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Origen_Fabrica> Origen_Fabrica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Origen_Traspaso> Origen_Traspaso { get; set; }
    }
}
