//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automotriz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoAccesorio
    {
        public int IdAutoAccesorio { get; set; }
        public Nullable<int> IdAccesorio { get; set; }
        public Nullable<int> IdAutomovil { get; set; }
    
        public virtual Accesorio Accesorio { get; set; }
        public virtual Automovil Automovil { get; set; }
    }
}
