//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automotriz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autoparte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Autoparte()
        {
            this.Manten_Autopar = new HashSet<Manten_Autopar>();
        }
    
        public int IdAutopartes { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Cantidad_Total { get; set; }
        public Nullable<int> IdCategoriaAutoparte { get; set; }
        public Nullable<int> IdConcesinaria { get; set; }
    
        public virtual CategoriaAutoparte CategoriaAutoparte { get; set; }
        public virtual Concesinaria Concesinaria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manten_Autopar> Manten_Autopar { get; set; }
    }
}
