//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automotriz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoCliente
    {
        public int IdAutoCliente { get; set; }
        public Nullable<int> IdAutomovil { get; set; }
        public Nullable<int> IdVentaAuto { get; set; }
        public Nullable<int> IdPromocion_Auto { get; set; }
        public Nullable<bool> Promo { get; set; }
    
        public virtual Automovil Automovil { get; set; }
        public virtual Promocion_Auto Promocion_Auto { get; set; }
        public virtual VentaAuto VentaAuto { get; set; }
    }
}
