//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automotriz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Referencias = new HashSet<Referencia>();
            this.VentaAutoes = new HashSet<VentaAuto>();
        }
    
        public int IdCliente { get; set; }
        public Nullable<int> Numero { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public Nullable<System.DateTime> FechaNac { get; set; }
        public string Sexo { get; set; }
        public string TelCasa { get; set; }
        public string TelCel { get; set; }
        public string Correo { get; set; }
        public string RFC { get; set; }
        public Nullable<int> IdMunicipio { get; set; }
        public Nullable<int> IdEstado_Cliente { get; set; }
    
        public virtual Estado_Cliente Estado_Cliente { get; set; }
        public virtual Municipio Municipio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Referencia> Referencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentaAuto> VentaAutoes { get; set; }
    }
}
