//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automotriz.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConcesionariaEntities : DbContext
    {
        public ConcesionariaEntities()
            : base("name=ConcesionariaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accesorio> Accesorios { get; set; }
        public virtual DbSet<AccesorioList> AccesorioLists { get; set; }
        public virtual DbSet<Anio> Anios { get; set; }
        public virtual DbSet<AutoAccesorio> AutoAccesorios { get; set; }
        public virtual DbSet<AutoCliente> AutoClientes { get; set; }
        public virtual DbSet<AutoColorList> AutoColorLists { get; set; }
        public virtual DbSet<AutoEstadoList> AutoEstadoLists { get; set; }
        public virtual DbSet<AutoMarca> AutoMarcas { get; set; }
        public virtual DbSet<AutoModelo> AutoModeloes { get; set; }
        public virtual DbSet<Automovil> Automovils { get; set; }
        public virtual DbSet<Autoparte> Autopartes { get; set; }
        public virtual DbSet<CategoriaAutoparte> CategoriaAutopartes { get; set; }
        public virtual DbSet<Concesinaria> Concesinarias { get; set; }
        public virtual DbSet<Empleado> Empleadoes { get; set; }
        public virtual DbSet<eRROR> eRRORs { get; set; }
        public virtual DbSet<Estado> Estadoes { get; set; }
        public virtual DbSet<Estado_Cliente> Estado_Cliente { get; set; }
        public virtual DbSet<EstadoVenta> EstadoVentas { get; set; }
        public virtual DbSet<Fabrica> Fabricas { get; set; }
        public virtual DbSet<Manten_Autopar> Manten_Autopar { get; set; }
        public virtual DbSet<MantenEstado> MantenEstadoes { get; set; }
        public virtual DbSet<Mantenimiento> Mantenimientoes { get; set; }
        public virtual DbSet<Municipio> Municipios { get; set; }
        public virtual DbSet<Origen_Fabrica> Origen_Fabrica { get; set; }
        public virtual DbSet<Origen_Traspaso> Origen_Traspaso { get; set; }
        public virtual DbSet<OrigenEstado> OrigenEstadoes { get; set; }
        public virtual DbSet<Pai> Pais { get; set; }
        public virtual DbSet<Promocion_Auto> Promocion_Auto { get; set; }
        public virtual DbSet<PromocionList> PromocionLists { get; set; }
        public virtual DbSet<Referencia> Referencias { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TipoEmpleado> TipoEmpleadoes { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<VentaAuto> VentaAutoes { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
    }
}
