//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automotriz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public int IdEmpleado { get; set; }
        public string Numero { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public Nullable<bool> C_Estado { get; set; }
        public Nullable<int> IdTipoEmpleado { get; set; }
        public Nullable<int> IdConcesinaria { get; set; }
    
        public virtual Concesinaria Concesinaria { get; set; }
        public virtual TipoEmpleado TipoEmpleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
