//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automotriz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manten_Autopar
    {
        public int IdManten_Autopar { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> IdMantenimiento { get; set; }
        public Nullable<int> IdAutopartes { get; set; }
        public Nullable<int> Cantidad_Autopartes { get; set; }
    
        public virtual Autoparte Autoparte { get; set; }
        public virtual Mantenimiento Mantenimiento { get; set; }
    }
}
