//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automotriz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Origen_Fabrica
    {
        public int IdOrigen_Fabrica { get; set; }
        public string Numero { get; set; }
        public Nullable<int> IdFabrica { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdAutomovil { get; set; }
        public Nullable<int> IdOrigenEstado { get; set; }
    
        public virtual Automovil Automovil { get; set; }
        public virtual Fabrica Fabrica { get; set; }
        public virtual OrigenEstado OrigenEstado { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
