//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automotriz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Origen_Traspaso
    {
        public int IdOrigen_Traspaso { get; set; }
        public string Numero { get; set; }
        public Nullable<int> IdVendedor { get; set; }
        public Nullable<int> IdComprador { get; set; }
        public Nullable<int> IdConcesinaria { get; set; }
        public Nullable<int> IdAutomovil { get; set; }
        public Nullable<int> IdOrigenEstado { get; set; }
    
        public virtual Automovil Automovil { get; set; }
        public virtual Concesinaria Concesinaria { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual OrigenEstado OrigenEstado { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
