//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automotriz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromocionList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PromocionList()
        {
            this.Promocion_Auto = new HashSet<Promocion_Auto>();
        }
    
        public int IdPromocion { get; set; }
        public string Numero { get; set; }
        public Nullable<int> Cantidad_Auto { get; set; }
        public Nullable<int> Descuento { get; set; }
        public Nullable<System.DateTime> FechaVigencia { get; set; }
        public Nullable<bool> Tipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Promocion_Auto> Promocion_Auto { get; set; }
    }
}
